name: Delete Untagged Container Versions

on:
  workflow_dispatch:
    inputs:
      package_name:
        required: true
        type: string
      package_type:
        required: true
        type: string
        default: container
      min_versions_to_keep:
        required: false
        type: number
        default: 4
  
  workflow_call:
    inputs:
      package_name:
        required: true
        type: string
      package_type:
        required: true
        type: string
        default: container
      min_versions_to_keep:
        required: false
        type: number
        default: 4

jobs:
  delete_versions:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Delete all untagged container versions
        uses: actions/delete-package-versions@v5
        with:
          delete-only-untagged-versions: 'false'
          min-versions-to-keep: ${{ inputs.min_versions_to_keep }}
          package-name: ${{ inputs.package_name }}
          package-type: ${{ inputs.package_type }}
