name: Pull/Run Unit tests

on:
  workflow_dispatch:
  pull_request_target:
    types: [opened, reopened, edited]
  workflow_call:
permissions:
  contents: write
jobs:
  test:
    runs-on: ubuntu-latest
    name: 'Test E2E'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20.x
      - name: Install mosquitto client
        run: |
          sudo apt update
          sudo apt install -y mosquitto mosquitto-clients
      - name: npm run build
        run: |
          npm ci
          npm run build
          npm run e2e:start
      - name: Cypress run e2e test
        uses: cypress-io/github-action@v6
      - name: Screenshots cypress
        if: ${{ always()}}
        uses: actions/upload-artifact@v4
        with:
          name: e2e-screenshots
          path: cypress/screenshots/
          retention-days: 1
      - name: Protocol from starting servers
        if: ${{ always()}}
        uses: actions/upload-artifact@v4
        with:
          name: e2e-serverlogs
          path: e2e/
          retention-days: 1
      - name: Run jest component tests
        run: npx jest --reporters default --reporters github-actions
      - name: Cypress run component tests
        uses: cypress-io/github-action@v6
        with:
          component: true
          install: false
      - name: Run jest component tests
        run: npx jest --reporters default --reporters github-actions
