name: Pull/Run Unit tests

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, edited]
  workflow_call:
permissions:
  contents: write
jobs:
  test:
    runs-on: ubuntu-latest
    name: 'Test E2E'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20.x
      - name: Install mosquitto client
        run: |
          sudo apt update
          sudo apt install -y mosquitto mosquitto-clients
      - name: Cypress run e2e test
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm run e2e:start
      - name: Protocol from starting servers
        run: cat nohup.out 
      - name: Run jest component tests
        run: npx jest --reporters default --reporters github-actions
      - name: Cypress run component tests
        uses: cypress-io/github-action@v6
        with:
          component: true
          install: false
      - name: Run jest component tests
        run: npx jest --reporters default --reporters github-actions

